/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airlinemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anmol
 */
public class Book_Ticket extends javax.swing.JInternalFrame {

    /**
     * Creates new form Book_Ticket
     */
    public Book_Ticket() {
        initComponents();
        autoId();
    }

    public void autoId() {
        Connection con;
        PreparedStatement pre;
        try {
            //legacy class com.mysql.jdbc.Driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlinedatabase", "root", "1234");
            //allow us to create statement with the help of this we can execute query
            Statement s = (Statement) con.createStatement();
            //store res of query here query is executed with help of jdbc driver
            ResultSet rs = s.executeQuery("Select MAX(TicketId) from tickets");
            rs.next();
            //INITAL CUSOMER ID WHEN THERE IS NO CUST ID IN DB or when db is empty
            if (rs.getString("MAX(TicketId)") == null) {
                //text var customer id
                ticket_id.setText("TS001");
            } else {
                //get last id or max id from db add+1 to it
                long id = Long.parseLong(rs.getString("MAX(TicketId)").substring(2, rs.getString("MAX(TicketId)").length()));
                id++;
                ticket_id.setText("TS" + String.format("%03d", id));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arrival = new javax.swing.JComboBox<>();
        departure = new javax.swing.JComboBox<>();
        SeachButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ticket_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        customer_id = new javax.swing.JTextField();
        SearchCustomer = new javax.swing.JButton();
        first_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        seats = new javax.swing.JSpinner();
        BookTicket = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        total_fare = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Book Ticket");

        jLabel2.setText("Arrival");

        jLabel3.setText("Departure");

        arrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Goa", "Chennai", "Mumbai" }));

        departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Goa", "Chennai", "Mumbai" }));

        SeachButton.setText("Search");
        SeachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeachButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Flight Name", "Arrival", "Departure", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Ticket Id");

        jLabel5.setText("Customer Id");

        SearchCustomer.setText("Search");
        SearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerActionPerformed(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("LastName");

        jLabel8.setText("Contact");

        jLabel9.setText("Gender");

        jLabel10.setText("Fare");

        jLabel11.setText("No. of Tickets");

        fare.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fareCaretUpdate(evt);
            }
        });

        seats.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seatsStateChanged(evt);
            }
        });

        BookTicket.setText("Book");
        BookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicketActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");

        jLabel12.setText("Total Fare");

        total_fare.setText("total_fare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(SeachButton)))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_id, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(first_name)
                            .addComponent(last_name)
                            .addComponent(contact)
                            .addComponent(gender)
                            .addComponent(fare)
                            .addComponent(seats)
                            .addComponent(total_fare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78)
                        .addComponent(ticket_id, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(SearchCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(BookTicket)
                        .addGap(31, 31, 31)
                        .addComponent(jButton4)))
                .addGap(0, 103, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ticket_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCustomer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(SeachButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(total_fare))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookTicket)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeachButtonActionPerformed
        Connection con;
        PreparedStatement pre = null;

        String Arrival = arrival.getSelectedItem().toString();
        String Departure = departure.getSelectedItem().toString();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect to db
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlinedatabase", "root", "1234");
            //create state for interaction with db
            Statement s = con.createStatement();

            pre = con.prepareStatement("select * from flights where Arrival=? && Depature=?");
            pre.setString(1, Arrival);
            pre.setString(2, Departure);
            //storing res in resultset
            ResultSet rs = pre.executeQuery();
            //get meta data from result set
            ResultSetMetaData RSMD = rs.getMetaData();
            //cc stands for table column that we fetch from meta data
            int cc = RSMD.getColumnCount();
            //using table to show data
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            //initial row is at 0 index
            DFT.setRowCount(0);

            Vector<String> list = new Vector<>();
            while (rs.next()) {

                for (int i = 1; i <= cc; i++) {

                    list.add(rs.getString("FlightId"));
                    list.add(rs.getString("FlightName"));
                    list.add(rs.getString("Arrival"));
                    list.add(rs.getString("Depature"));
                    list.add(rs.getString("Date"));
                }
                DFT.addRow(list);
            }

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SeachButtonActionPerformed

    private void fareCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fareCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_fareCaretUpdate

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // if mouse is clicked on table
        int column = 0;
        //get ob the row that mouse has selected
        int row = jTable1.getSelectedRow();
        //get that particular value of that row
        String value = jTable1.getModel().getValueAt(row, column).toString();

        //connecting backend
        Connection con;
        PreparedStatement pre = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect to db
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlinedatabase", "root", "1234");
            //create state for interaction with db
            Statement s = con.createStatement();

            pre = con.prepareStatement("select * from flights where FlightId=?");
            pre.setString(1, value);

            ResultSet rs = pre.executeQuery();
            rs.next();
            fare.setText(rs.getString("Fare"));

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void seatsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seatsStateChanged
        //No of tickets spinner
        int value = (int) seats.getValue();
        int price = Integer.parseInt(fare.getText());
        int total = value * price;
        total_fare.setText(String.valueOf(total));


    }//GEN-LAST:event_seatsStateChanged

    private void BookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicketActionPerformed
        // TODO add your handling code here:

        Connection con;
        PreparedStatement pre = null;

        String Arrival = arrival.getSelectedItem().toString();
        String Departure = departure.getSelectedItem().toString();
        String CustId = customer_id.getText();

        // if mouse is clicked on table 
        //initial value is 0
        int columnForFare = 0;
        //get ob the row that mouse has selected
        int row = jTable1.getSelectedRow();
        //get that particular value of that row
        String FlightId = jTable1.getModel().getValueAt(row, columnForFare).toString();
        String TicketId = ticket_id.getText();
        int Seats = (int) seats.getValue();
        int columnForDate = 4;
        int rowForDate = jTable1.getSelectedRow();
        String Date = jTable1.getModel().getValueAt(rowForDate, columnForDate).toString();
        String TotalAmount = total_fare.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect to db
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlinedatabase", "root", "1234");
            //create state for interaction with db
            Statement s = con.createStatement();

            pre = con.prepareStatement("insert into tickets(TicketId,CustomerId,FlightId,Arrival,Departure,Date,Seats,TotalAmount) values(?,?,?,?,?,?,?,?)");
            pre.setString(1, TicketId);
            pre.setString(2, CustId);
            pre.setString(3, FlightId);
            pre.setString(4, Arrival);
            pre.setString(5, Departure);
            pre.setString(6, String.valueOf(Seats));
            pre.setString(7, Date);
            pre.setString(8, TotalAmount);

            pre.executeUpdate();

            JOptionPane.showMessageDialog(null, "Ticket Booked");

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BookTicketActionPerformed

    private void SearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerActionPerformed
        //Search Customer

        Connection con;
        PreparedStatement pre = null;
        try {
            String ID = customer_id.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            //connect to db
            con = DriverManager.getConnection("jdbc:mysql://localhost/airlinedatabase", "root", "1234");

            pre = con.prepareStatement("Select * from customers where Customerid=?");
            pre.setString(1, ID);
            //getting result
            ResultSet rs = pre.executeQuery();
            rs.next();

            first_name.setText(rs.getString("FirstName"));
            last_name.setText(rs.getString("LastName"));
            contact.setText(rs.getString("Contact"));
            gender.setText(rs.getString("Gender"));

        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SearchCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookTicket;
    private javax.swing.JButton SeachButton;
    private javax.swing.JButton SearchCustomer;
    private javax.swing.JComboBox<String> arrival;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField customer_id;
    private javax.swing.JComboBox<String> departure;
    private javax.swing.JTextField fare;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField last_name;
    private javax.swing.JSpinner seats;
    private javax.swing.JTextField ticket_id;
    private javax.swing.JLabel total_fare;
    // End of variables declaration//GEN-END:variables
}
